### ISSUE TITLE
About the untarget part in your CW code

### ISSUE THREAD

**Issue by Soton-Alex** [Carco-git/CW_Attack_on_MNIST#1]
Hello!

I am Chinese, too. 
我也在尝试MNIST复现CW攻击，在你的代码中，
当未选择目标时，正确分类是0的数字依旧有L2loss的输出，请问下这是为什么？
以及同样当未选择目标时，对正确分类为非0的其他数字，CW函数没办法生成对应的
对抗样本。

麻烦大佬给个讲解？这两个情况出现的原因是什么呢。。。
谢谢你！

Thank you so much!
Best wishes.

**Comment by Carco-git** [comment]
您好，


关于提到的第一个问题，请尝试打印一下real和second的值，可以观察得到，具体的原因我已经记不太清。
关于第二个问题，是我提交时候的疏忽，当预测值不为0时，需要把
def cwattack_l2(img,model,right_label,iteration=1000,lr=0.001,target=False,target_label=0):
中的target_label置为标签值，此处会影响tlab*output的结果。即如果数字4的话，改为target_label=4。
我会在明天提交一个新的版本修复这个问题。


谢谢你的提醒，祝好
On 8/24/2020 22:20，Alex-mtttttt<notifications@github.com> wrote：

Hello!

I am Chinese, too.
我也在尝试MNIST复现CW攻击，在你的代码中，
当未选择目标时，正确分类是0的数字依旧有L2loss的输出，请问下这是为什么？
以及同样当未选择目标时，对正确分类为非0的其他数字，CW函数没办法生成对应的
对抗样本。

麻烦大佬给个讲解？这两个情况出现的原因是什么呢。。。
谢谢你！

Thank you so much!
Best wishes.

**Comment by Soton-Alex** [comment]
> 您好， 关于提到的第一个问题，请尝试打印一下real和second的值，可以观察得到，具体的原因我已经记不太清。 关于第二个问题，是我提交时候的疏忽，当预测值不为0时，需要把 def cwattack_l2(img,model,right_label,iteration=1000,lr=0.001,target=False,target_label=0): 中的target_label置为标签值，此处会影响tlab*output的结果。即如果数字4的话，改为target_label=4。 我会在明天提交一个新的版本修复这个问题。 谢谢你的提醒，祝好 On 8/24/2020 22:20，Alex-mtttttt<notifications@github.com> wrote： Hello! I am Chinese, too. 我也在尝试MNIST复现CW攻击，在你的代码中， 当未选择目标时，正确分类是0的数字依旧有L2loss的输出，请问下这是为什么？ 以及同样当未选择目标时，对正确分类为非0的其他数字，CW函数没办法生成对应的 对抗样本。 麻烦大佬给个讲解？这两个情况出现的原因是什么呢。。。 谢谢你！ Thank you so much! Best wishes. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

懂了懂了，感恩，谢大佬提点
