### ISSUE TITLE
Blog 无法访问

### ISSUE THREAD

**Issue by userElaina** [Carco-git/CW_Attack_on_MNIST#2]
您好，RADME 中链接的 blog 无法访问，域名指向一家公司。请问方便提供您的新博客地址，或者这篇论文有关的博文内容吗？非常感谢。

**Comment by Carco-git** [comment]
Hi, 不好意思我之前的博客域名没有续费所以没有继续维护了，如果现在还需要的话可以提供你的邮箱地址，我可以把markdown给你

**Comment by userElaina** [comment]
这是我的邮箱: `userelaina@gmail.com`
谢谢.

**Comment by userElaina** [comment]
已收到，非常感谢。
